GET https://herme-io.herokuapp.com/getall/

###

GET http://localhost:4000/dash
Authorization: eyJhbGciOiJIUzI1NiJ9.YWR4bA.bR3AWqNvcoxyyywLa8B6O-WEqKGGjptR84AbpcjlQ5A

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "joe",
    "email" : "joe@gmail.com",
    "firstName": "Joe",
    "lastName": "Dalton",
    "password": "password"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "adxl",
    "password": "pass"
}

###

POST https://herme-io.herokuapp.com/login
Content-Type: application/json

{
    "username": "joe",
    "password": "password"
}

###
DELETE http://localhost:3000/genocide