GET https://herme-io.herokuapp.com/getall/

###

GET http://localhost:3000/dash
Authorization: eyJhbGciOiJIUzI1NiJ9.am9l.YuigTd6kMTvmoaZyZ0_ItpmlwwEJk9HOtOf5k_-VDPQ

###

POST http://localhost:4000/register
Content-Type: application/json

{
    "username": "joe",
    "email" : "joe@gmail.com",
    "firstName": "Joe",
    "lastName": "Dalton",
    "password": "password"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "joe",
    "password": "password"
}

###

POST https://herme-io.herokuapp.com/login
Content-Type: application/json

{
    "username": "joe",
    "password": "password"
}

###
DELETE http://localhost:3000/genocide